/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogContent: typeof import('./src/components/Blog/View/BlogContent.vue')['default']
    BlogForm: typeof import('./src/components/Blog/Create/BlogForm.vue')['default']
    BlogList: typeof import('./src/components/Blog/View/BlogList.vue')['default']
    Book3D: typeof import('./src/components/Utils/Book3D.vue')['default']
    BooksComentarios: typeof import('./src/components/Book/BooksComentarios.vue')['default']
    ChapterBlock: typeof import('./src/components/Blog/Create/ChapterBlock.vue')['default']
    ChapterPagination: typeof import('./src/components/Blog/View/ChapterPagination.vue')['default']
    ChatBotWidget: typeof import('./src/components/Chat/ChatBotWidget.vue')['default']
    ChatPanel: typeof import('./src/components/Chat/ChatPanel.vue')['default']
    ClassicCard: typeof import('./src/components/Blog/View/ListBlogs/FolderTemplates/ClassicCard.vue')['default']
    ComingSoon: typeof import('./src/components/Utils/ComingSoon.vue')['default']
    ConfirmEmail: typeof import('./src/components/Auth/ConfirmEmail.vue')['default']
    DataUserForm: typeof import('./src/components/Sim/DataUserForm.vue')['default']
    EditorJs: typeof import('./src/components/Blog/Create/EditorJs.vue')['default']
    Flashcards: typeof import('./src/components/Utils/Flashcards.vue')['default']
    FolderRenderer: typeof import('./src/components/Blog/View/ListBlogs/FolderRenderer.vue')['default']
    ForgotPassword: typeof import('./src/components/Auth/ForgotPassword.vue')['default']
    GlassCard: typeof import('./src/components/Blog/View/ListBlogs/FolderTemplates/GlassCard.vue')['default']
    LoginForm: typeof import('./src/components/Auth/LoginForm.vue')['default']
    NeonCard: typeof import('./src/components/Blog/View/ListBlogs/FolderTemplates/NeonCard.vue')['default']
    PageSidebar: typeof import('./src/components/Blog/View/PageSidebar.vue')['default']
    PaperCard: typeof import('./src/components/Blog/View/ListBlogs/FolderTemplates/PaperCard.vue')['default']
    QuizPlayer: typeof import('./src/components/Utils/QuizPlayer.vue')['default']
    RegisterForm: typeof import('./src/components/Auth/RegisterForm.vue')['default']
    ResetPasswordForm: typeof import('./src/components/Auth/ResetPasswordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowSlider: typeof import('./src/components/Blog/View/ListBlogs/RowSlider.vue')['default']
    SectionPlacement: typeof import('./src/components/Blog/View/ListBlogs/SectionPlacement.vue')['default']
    SidebarNav: typeof import('./src/components/Blog/View/SidebarNav.vue')['default']
    SuggestTaxonModal: typeof import('./src/components/Blog/Create/modals/SuggestTaxonModal.vue')['default']
    SurveyForm: typeof import('./src/components/Utils/SurveyForm.vue')['default']
    TagInput: typeof import('./src/components/Blog/Create/inputs/TagInput.vue')['default']
    TheAreaBlogs: typeof import('./src/components/Home/TheAreaBlogs.vue')['default']
    TheAreaBooks: typeof import('./src/components/Home/TheAreaBooks.vue')['default']
    TheAreaTrabajos: typeof import('./src/components/Home/TheAreaTrabajos.vue')['default']
    TheAreaVideos: typeof import('./src/components/Home/TheAreaVideos.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/Home/TheHeader.vue')['default']
    ThemeSwitcher: typeof import('./src/components/Blog/View/ThemeSwitcher.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    UserCard: typeof import('./src/components/Utils/UserCard.vue')['default']
  }
}
