/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/blogView': RouteRecordInfo<'/blogView', '/blogView', Record<never, never>, Record<never, never>>,
    '/confirmationRequired': RouteRecordInfo<'/confirmationRequired', '/confirmationRequired', Record<never, never>, Record<never, never>>,
    '/cuestionario': RouteRecordInfo<'/cuestionario', '/cuestionario', Record<never, never>, Record<never, never>>,
    '/librosView': RouteRecordInfo<'/librosView', '/librosView', Record<never, never>, Record<never, never>>,
    '/protected_route': RouteRecordInfo<'/protected_route', '/protected_route', Record<never, never>, Record<never, never>>,
    '/simulador': RouteRecordInfo<'/simulador', '/simulador', Record<never, never>, Record<never, never>>,
  }
}
